/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CronPicker {
    }
}
declare global {
    interface HTMLCronPickerElement extends Components.CronPicker, HTMLStencilElement {
    }
    var HTMLCronPickerElement: {
        prototype: HTMLCronPickerElement;
        new (): HTMLCronPickerElement;
    };
    interface HTMLElementTagNameMap {
        "cron-picker": HTMLCronPickerElement;
    }
}
declare namespace LocalJSX {
    interface CronPicker {
    }
    interface IntrinsicElements {
        "cron-picker": CronPicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cron-picker": LocalJSX.CronPicker & JSXBase.HTMLAttributes<HTMLCronPickerElement>;
        }
    }
}
